language: node_js
node_js:
    - "11"
install:
    - npm install
after_script:
    - cd ./dist
    - git init
    - git config user.name "yxx"
    - git config user.email "1330709131@qq.com"
    - git add -A
    - git commit -m "update"
    - git push --force "https://${GH_TOKEN}@${GH_REF}" "master:gh-pages"
branches:
    only:
        - master